apiVersion: v1
kind: Pod
metadata:
  name: demo2
  namespace: dem
spec:
  containers:
  - name: c1
    image: busybox
    command: ["sleep","3000"]
    volumeMounts:
    - mountPath: /host-data
      name: hostvol
  volumes:
  - name: hostvol
    hostPath:
      path: /demo2/c1
      type: DirectoryOrCreate
