apiVersion: v1
kind: Pod
metadata:
  name: demo1
  namespace: dem
spec:
  containers:
  - name: app1
    image: nginx
    volumeMounts:
    - mountPath: /tmp/con1
      name: myvol
  - name: app2
    image: nginx
    command: ["sleep","2000"]
    volumeMounts:
    - mountPath: /tmp/con2
      name: myvol
  volumes:
  - name: myvol
    emptyDir: {}
