apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvcdemo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: ""
  volumeName: pvdemo
