apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  namespace: nfs-ns
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: 13.232.139.212
    path: /nfs-storage
