apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfspvc
  namespace: nfs-ns
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 100Mi

